"use client"

import { FormEvent, useState } from "react"
import { useRouter } from "next/navigation"
import { Award, Pencil } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { formatCompactDateInput } from "@/lib/compact-date"
import type { CompetitionPersonOption } from "@/lib/competition-people"
import type { Option } from "@/lib/competitions-v2"
import type { SheetRow } from "@/lib/google-sheets"

const clean = (value: unknown) => String(value ?? "").trim()
const norm = (value: string) => value.toUpperCase()
export function CompetitionDistinctionManager({ competitionId, closed, unitLabels, types, targets, events, phases, matches, units, people, distinctions }: { competitionId: string; closed: boolean; unitLabels: Record<string, string>; types: Option[]; targets: Record<string, string>; events: SheetRow[]; phases: SheetRow[]; matches: SheetRow[]; units: SheetRow[]; people: CompetitionPersonOption[]; distinctions: SheetRow[] }) {
  const router = useRouter(), [open, setOpen] = useState(false), [editing, setEditing] = useState<SheetRow | null>(null), [pending, setPending] = useState(false), [form, setForm] = useState<Record<string, string>>({ statut: "ACTIF" })
  const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value, ...(key === "id_type_distinction" ? { id_unite_competition: "", id_acteur: "", id_type_acteur: "" } : {}), ...(key === "id_epreuve_competition" ? { id_phase_competition: "", id_match: "", id_unite_competition: "" } : {}), ...(key === "id_phase_competition" ? { id_match: "" } : {}) }))
  const target = norm(targets[form.id_type_distinction] ?? ""), allowUnit = target.includes("UNITE"), allowActor = target.includes("ATHLETE") || target.includes("COACH") || target.includes("ACTEUR")
  const visiblePeople = people.filter((person) => target !== "ATHLETE" || norm(person.typeLabel).includes("ATHLETE")).filter((person) => target !== "COACH" || norm(person.typeLabel).includes("COACH") || norm(person.typeLabel).includes("ENTRAINEUR"))
  const availablePhases = phases.filter((row) => !form.id_epreuve_competition || clean(row.id_epreuve_competition) === form.id_epreuve_competition), availableMatches = matches.filter((row) => (!form.id_phase_competition || clean(row.id_phase_competition) === form.id_phase_competition) && (!form.id_epreuve_competition || availablePhases.some(phase => clean(phase.id_phase_competition) === clean(row.id_phase_competition)))), availableUnits = units.filter((row) => !form.id_epreuve_competition || clean(row.id_epreuve_competition) === form.id_epreuve_competition)
  const unitLabel = (row: SheetRow) => unitLabels[clean(row.id_unite_competition)] || clean(row.id_club) || clean(row.id_equipe_nationale_saison) || clean(row.id_unite_competition)
  function startEdit(row: SheetRow) { setEditing(row); setForm({ statut: clean(row.statut), observations: clean(row.observations) }); setOpen(true) }
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); try { const suffix = editing ? `/${encodeURIComponent(clean(editing.id_distinction_competition))}` : "", response = await fetch(`/api/competitions/${encodeURIComponent(competitionId)}/distinctions${suffix}`, { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }), payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Enregistrement impossible."); toast.success(editing ? "Distinction modifiée" : "Distinction attribuée"); setOpen(false); setEditing(null); setForm({ statut: "ACTIF" }); router.refresh() } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Enregistrement impossible.") } finally { setPending(false) } }
  if (closed) return null
  return <><div className="flex justify-end"><Button onClick={() => { setEditing(null); setForm({ statut: "ACTIF" }); setOpen(true) }} className="bg-brand-gold text-slate-950 hover:bg-brand-gold/90"><Award className="size-4" />Attribuer une distinction</Button></div>
    <div className="grid gap-2">{distinctions.map((row) => <div key={clean(row.id_distinction_competition)} className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span>{types.find((type) => type.id === clean(row.id_type_distinction))?.label ?? clean(row.id_type_distinction)}</span><Button variant="ghost" size="icon" onClick={() => startEdit(row)} aria-label="Modifier la distinction"><Pencil className="size-4" /></Button></div>)}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{editing ? "Modifier la distinction" : "Attribuer une distinction"}</DialogTitle><DialogDescription>Le bénéficiaire autorisé dépend du type sélectionné.</DialogDescription></DialogHeader><form id="distinction-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2">
      {editing ? <><Choice label="Statut" value={form.statut} options={[{ id: "ACTIF", label: "Actif" }, { id: "INACTIF", label: "Inactif" }]} onChange={(value) => set("statut", value)} /></> : <><Choice label="Type" value={form.id_type_distinction} options={types} onChange={(value) => set("id_type_distinction", value)} /><Choice label="Épreuve (facultatif)" value={form.id_epreuve_competition} options={events.map((row) => ({ id: clean(row.id_epreuve_competition), label: clean(row.nom_epreuve) }))} onChange={(value) => set("id_epreuve_competition", value)} />{allowUnit ? <Choice label="Unité bénéficiaire" value={form.id_unite_competition} options={availableUnits.map((row) => ({ id: clean(row.id_unite_competition), label: unitLabel(row) }))} onChange={(value) => set("id_unite_competition", value)} /> : null}{allowActor ? <Choice label="Acteur bénéficiaire" value={form.id_acteur} options={visiblePeople.map((person) => ({ id: person.id, label: `${person.label} · ${person.typeLabel}` }))} onChange={(value) => { const person = visiblePeople.find((item) => item.id === value); setForm((current) => ({ ...current, id_acteur: value, id_type_acteur: person?.typeId ?? "" })) }} /> : null}<Choice label="Phase (facultatif)" value={form.id_phase_competition} options={availablePhases.map((row) => ({ id: clean(row.id_phase_competition), label: clean(row.nom_phase) }))} onChange={(value) => set("id_phase_competition", value)} /><Choice label="Match (facultatif)" value={form.id_match} options={availableMatches.map((row) => ({ id: clean(row.id_match), label: clean(row.id_match) }))} onChange={(value) => set("id_match", value)} /><Field label="Date d’attribution"><Input inputMode="numeric" maxLength={10} placeholder="JJMMAAAA" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" value={form.date_attribution ?? ""} onChange={(e) => set("date_attribution", formatCompactDateInput(e.target.value))} /></Field></>}
      <Field label="Observations" wide><Textarea value={form.observations ?? ""} onChange={(e) => set("observations", e.target.value)} /></Field>
    </form><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Annuler</Button><Button form="distinction-form" disabled={pending} className="bg-brand-gold text-slate-950 hover:bg-brand-gold/90">{pending ? "Enregistrement..." : editing ? "Modifier" : "Attribuer"}</Button></DialogFooter></DialogContent></Dialog>
  </>
}
function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <div className={wide ? "space-y-2 sm:col-span-2" : "space-y-2"}><Label>{label}</Label>{children}</div> }
function Choice({ label, value, options, onChange }: { label: string; value?: string; options: Option[]; onChange: (value: string) => void }) { return <Field label={label}><Select value={value ?? ""} onValueChange={onChange}><SelectTrigger className="w-full"><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{options.map((item) => <SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select></Field> }
