"use client"

import { FormEvent, useState } from "react"
import { useRouter } from "next/navigation"
import { Calculator, MoveRight } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { formatCompactDateInput } from "@/lib/compact-date"
import type { SheetRow } from "@/lib/google-sheets"

const clean = (value: unknown) => String(value ?? "").trim()
export function CompetitionStandingsManager({ competitionId, closed, phases, groups, units, phaseUnits, matches }: { competitionId: string; closed: boolean; phases: SheetRow[]; groups: SheetRow[]; units: SheetRow[]; phaseUnits: SheetRow[]; matches: SheetRow[] }) {
  const router = useRouter(), [mode, setMode] = useState<"calculate" | "qualify" | null>(null), [form, setForm] = useState<Record<string, string>>({}), [pending, setPending] = useState(false)
  const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value, ...(key === "id_phase_source" ? { id_unite_competition: "", id_phase_competition: "", id_groupe: "" } : {}), ...(key === "id_phase_competition" ? { id_groupe: "" } : {}) }))
  const groupPhases = phases.filter((row) => clean(row.id_mode_phase) === "MPH001"), selectedPhase = phases.find((row) => clean(row.id_phase_competition) === (mode === "calculate" ? form.id_phase_competition : form.id_phase_source))
  const sourceUnits = phaseUnits.filter((row) => clean(row.id_phase_competition) === form.id_phase_source && clean(row.statut) === "ACTIF").map((row) => clean(row.id_unite_competition))
  const destinations = phases.filter((row) => clean(row.id_epreuve_competition) === clean(selectedPhase?.id_epreuve_competition) && Number(clean(row.numero_phase)) > Number(clean(selectedPhase?.numero_phase)) && clean(row.statut) === "ACTIF")
  const destination = destinations.find((row) => clean(row.id_phase_competition) === form.id_phase_competition), unitLabel = (id: string) => { const unit = units.find((row) => clean(row.id_unite_competition) === id); return clean(unit?.id_club) || clean(unit?.id_equipe_nationale_saison) || id }
  async function submit(event: FormEvent) { event.preventDefault(); if (!mode) return; setPending(true); try { const response = await fetch(`/api/competitions/${encodeURIComponent(competitionId)}/standings`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, action: mode }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Opération impossible."); toast.success(mode === "calculate" ? "Classement recalculé" : "Unité qualifiée"); setMode(null); setForm({}); router.refresh() } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Opération impossible.") } finally { setPending(false) } }
  if (closed) return null
  return <><div className="flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={() => { setMode("qualify"); setForm({}) }}><MoveRight className="size-4" />Qualifier</Button><Button onClick={() => { setMode("calculate"); setForm({}) }} className="bg-brand-gold text-slate-950 hover:bg-brand-gold/90"><Calculator className="size-4" />Recalculer</Button></div><Dialog open={mode !== null} onOpenChange={(open) => !open && setMode(null)}><DialogContent><DialogHeader><DialogTitle>{mode === "calculate" ? "Recalculer un classement" : "Qualifier une unité"}</DialogTitle><DialogDescription>Le classement utilise uniquement les résultats joués et le barème du référentiel.</DialogDescription></DialogHeader><form id="standings-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2">
    {mode === "calculate" ? <><Choice label="Phase de groupes" value={form.id_phase_competition} options={groupPhases.map((row) => ({ id: clean(row.id_phase_competition), label: clean(row.nom_phase) }))} onChange={(value) => set("id_phase_competition", value)} /><Choice label="Groupe" value={form.id_groupe} options={groups.filter((row) => clean(row.id_phase_competition) === form.id_phase_competition).map((row) => ({ id: clean(row.id_groupe), label: clean(row.nom_groupe) }))} onChange={(value) => set("id_groupe", value)} /></> : <><Choice label="Phase source" value={form.id_phase_source} options={phases.map((row) => ({ id: clean(row.id_phase_competition), label: clean(row.nom_phase) }))} onChange={(value) => set("id_phase_source", value)} /><Choice label="Unité" value={form.id_unite_competition} options={[...new Set(sourceUnits)].map((id) => ({ id, label: unitLabel(id) }))} onChange={(value) => set("id_unite_competition", value)} /><Choice label="Phase destination" value={form.id_phase_competition} options={destinations.map((row) => ({ id: clean(row.id_phase_competition), label: clean(row.nom_phase) }))} onChange={(value) => set("id_phase_competition", value)} />{clean(destination?.id_mode_phase) === "MPH001" ? <Choice label="Groupe destination" value={form.id_groupe} options={groups.filter((row) => clean(row.id_phase_competition) === form.id_phase_competition).map((row) => ({ id: clean(row.id_groupe), label: clean(row.nom_groupe) }))} onChange={(value) => set("id_groupe", value)} /> : null}<Choice label="Match source (facultatif)" value={form.id_match_source} options={matches.filter((row) => clean(row.id_phase_competition) === form.id_phase_source).map((row) => ({ id: clean(row.id_match), label: clean(row.id_match) }))} onChange={(value) => set("id_match_source", value)} /><Field label="Date d’affectation"><Input inputMode="numeric" maxLength={10} placeholder="JJMMAAAA" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" value={form.date_affectation ?? ""} onChange={(e) => set("date_affectation", formatCompactDateInput(e.target.value))} /></Field><Field label="Observations" wide><Textarea value={form.observations ?? ""} onChange={(e) => set("observations", e.target.value)} /></Field></>}
  </form><DialogFooter><Button variant="outline" onClick={() => setMode(null)}>Annuler</Button><Button form="standings-form" disabled={pending} className="bg-brand-gold text-slate-950 hover:bg-brand-gold/90">{pending ? "Traitement..." : mode === "calculate" ? "Recalculer" : "Qualifier"}</Button></DialogFooter></DialogContent></Dialog></>
}
function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <div className={wide ? "space-y-2 sm:col-span-2" : "space-y-2"}><Label>{label}</Label>{children}</div> }
function Choice({ label, value, options, onChange }: { label: string; value?: string; options: Array<{ id: string; label: string }>; onChange: (value: string) => void }) { return <Field label={label}><Select value={value ?? ""} onValueChange={onChange}><SelectTrigger className="w-full"><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{options.map((item) => <SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select></Field> }
