"use client"
import { FormEvent, useState } from "react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Textarea } from "@/components/ui/textarea"
import { formatCompactDateInput } from "@/lib/compact-date"
import type { ActivityOption } from "@/lib/activities"
const initial = { id_type_activite: "", nom_activite: "", titre_public: "", resume: "", date_debut: "", date_fin: "", pays: "", ville: "", lieu: "", statut: "PLANIFIE", observations: "" }
export function ActivityForm({ open, onOpenChange, types }: { open: boolean; onOpenChange: (value: boolean) => void; types: ActivityOption[] }) {
  const router = useRouter(); const [form, setForm] = useState(initial); const [errors, setErrors] = useState<Record<string, string>>({}); const [pending, setPending] = useState(false)
  const set = (key: keyof typeof initial, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setErrors({}); try { const response = await fetch("/api/activities", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) { setErrors(payload.fields ?? {}); throw new Error(payload.error ?? "Création impossible.") } toast.success("Activité créée"); setForm(initial); onOpenChange(false); router.refresh() } catch (error) { toast.error(error instanceof Error ? error.message : "Création impossible.") } finally { setPending(false) } }
  const input = (label: string, key: keyof typeof initial, wide = false) => <div className={`space-y-2 ${wide ? "sm:col-span-2" : ""}`}><Label htmlFor={`activity-${key}`}>{label}</Label><Input id={`activity-${key}`} value={form[key]} onChange={(e) => set(key, e.target.value)} />{errors[key] ? <p className="text-xs text-destructive">{errors[key]}</p> : null}</div>
  const date = (label: string, key: "date_debut" | "date_fin") => <div className="space-y-2"><Label htmlFor={`activity-${key}`}>{label}</Label><Input id={`activity-${key}`} inputMode="numeric" maxLength={10} placeholder="JJMMAAAA" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" value={form[key]} onChange={(e) => set(key, formatCompactDateInput(e.target.value))} />{errors[key] ? <p className="text-xs text-destructive">{errors[key]}</p> : null}</div>
  return <Sheet open={open} onOpenChange={(next) => { onOpenChange(next); if (!next) { setForm(initial); setErrors({}) } }}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Créer une activité</SheetTitle><SheetDescription>Les séparateurs des dates sont ajoutés automatiquement.</SheetDescription></SheetHeader><form id="activity-create" onSubmit={submit} className="grid gap-4 px-4 sm:grid-cols-2"><div className="space-y-2"><Label>Type</Label><Select value={form.id_type_activite} onValueChange={(v) => set("id_type_activite", v)}><SelectTrigger className="w-full"><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{types.map((item) => <SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select>{errors.id_type_activite ? <p className="text-xs text-destructive">{errors.id_type_activite}</p> : null}</div>{input("Nom", "nom_activite")}{input("Titre public", "titre_public", true)}{date("Date de début", "date_debut")}{date("Date de fin", "date_fin")}{input("Pays", "pays")}{input("Ville", "ville")}{input("Lieu", "lieu", true)}<div className="space-y-2"><Label>Statut</Label><Select value={form.statut} onValueChange={(v) => set("statut", v)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{["PLANIFIE", "EN_COURS", "TERMINE", "REPORTE", "ANNULE"].map((v) => <SelectItem key={v} value={v}>{v.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label>Résumé</Label><Textarea value={form.resume} onChange={(e) => set("resume", e.target.value)} /></div><div className="space-y-2 sm:col-span-2"><Label>Observations</Label><Textarea value={form.observations} onChange={(e) => set("observations", e.target.value)} /></div></form><SheetFooter><Button form="activity-create" disabled={pending} className="bg-brand-gold text-slate-950 hover:bg-brand-gold/90">{pending ? "Création..." : "Créer"}</Button></SheetFooter></SheetContent></Sheet>
}
