"use client"
import { useState } from "react"
import { Pencil } from "lucide-react"
import { toast } from "sonner"
import { AvatarFileField,uploadAvatarFile } from "@/components/actors/avatar-file-field"
import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";import { Label } from "@/components/ui/label";import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";import { Sheet,SheetContent,SheetDescription,SheetFooter,SheetHeader,SheetTitle,SheetTrigger } from "@/components/ui/sheet"
import type { ActorSexOption } from "@/lib/actor-references";import { compactDateFromSheet,compareDateValues,formatCompactDateInput,formatDateForSheet,validateBirthDate } from "@/lib/compact-date";import type { Officiel } from "@/lib/types"
export type SavedOfficiel=Pick<Officiel,"idOfficiel"|"idSexe"|"idNational"|"idFivb"|"nomComplet"|"sexe"|"dateDeNaissance"|"lieuNaissance"|"nationalite"|"telephone"|"email"|"adresse"|"numeroPasseport"|"dateDelivrancePasseport"|"dateExpirationPasseport"|"observations"|"statut">&{avatarDriveId?:string;avatarDriveUrl?:string}
const dateError=(v:string,l:string)=>{if(!v)return "";try{formatDateForSheet(v);return ""}catch{return `${l} est invalide.`}}
export function OfficielFormDialog({officiel,sexes,onSaved}:{officiel?:Officiel;sexes:ActorSexOption[];onSaved:(o:SavedOfficiel)=>void}){const editing=!!officiel,initial=()=>({idNational:officiel?.idNational??"",idFivb:officiel?.idFivb??"",nomComplet:officiel?.nomComplet??"",idSexe:officiel?.idSexe??"",dateNaissance:compactDateFromSheet(officiel?.dateDeNaissance??""),lieuNaissance:officiel?.lieuNaissance??"",nationalite:officiel?.nationalite??"",telephone:officiel?.telephone??"",email:officiel?.email??"",adresse:officiel?.adresse??"",numeroPasseport:officiel?.numeroPasseport??"",dateDelivrancePasseport:compactDateFromSheet(officiel?.dateDelivrancePasseport??""),dateExpirationPasseport:compactDateFromSheet(officiel?.dateExpirationPasseport??""),statut:String(officiel?.statut||"ACTIF").toUpperCase(),observations:officiel?.observations??""});const[open,setOpen]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(""),[form,setForm]=useState(initial),[avatar,setAvatar]=useState<File|null>(null)
const submit=async(e:React.FormEvent)=>{e.preventDefault();const birth=validateBirthDate(form.dateNaissance);if(birth){setError(birth);return}const d=dateError(form.dateDelivrancePasseport,"La date de délivrance"),x=dateError(form.dateExpirationPasseport,"La date d’expiration");if(d||x){setError(d||x);return}if(form.dateDelivrancePasseport&&form.dateExpirationPasseport&&compareDateValues(form.dateDelivrancePasseport,form.dateExpirationPasseport)!>0){setError("L’expiration ne peut pas précéder la délivrance.");return}setPending(true);setError("");try{const r=await fetch(editing?`/api/officiels/${encodeURIComponent(officiel!.idOfficiel)}`:"/api/officiels",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),j=await r.json();if(!r.ok)throw new Error(j.message);let saved=j.officiel as SavedOfficiel;if(avatar)saved={...saved,...await uploadAvatarFile("officiel",saved.idOfficiel,avatar)};onSaved(saved);toast.success(j.message);setOpen(false);if(!editing)setForm(initial())}catch(c){const m=c instanceof Error?c.message:"Enregistrement impossible.";setError(m);toast.error(m)}finally{setPending(false)}}
const date=(key:"dateNaissance"|"dateDelivrancePasseport"|"dateExpirationPasseport",label:string)=><div className="space-y-2"><Label>{label}</Label><Input type="text" inputMode="numeric" autoComplete="off" maxLength={10} pattern="(?:[0-9]{2}/[0-9]{2}/[0-9]{4})?" title="Saisissez 8 chiffres ; la date est affichée au format JJ/MM/AAAA" placeholder="JJMMAAAA" value={form[key]} onChange={e=>setForm({...form,[key]:formatCompactDateInput(e.target.value)})}/></div>
return <Sheet open={open} onOpenChange={n=>{if(!pending){if(n){setForm(initial());setError("");setAvatar(null)}setOpen(n)}}}><SheetTrigger asChild><Button variant={editing?"outline":"default"} className={editing?undefined:"bg-brand-gold text-[#071827] hover:bg-brand-gold/90"}>{editing?<><Pencil className="mr-2 size-4"/>Modifier</>:"Créer un officiel"}</Button></SheetTrigger><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>{editing?"Modifier l’officiel":"Créer un officiel"}</SheetTitle><SheetDescription>Identité permanente de l’officiel. Le mandat se gère séparément.</SheetDescription></SheetHeader><form onSubmit={submit} className="space-y-6 px-4 pb-6"><div className="grid gap-4 md:grid-cols-2">{editing&&<div className="space-y-2"><Label>Identifiant</Label><Input disabled value={officiel!.idOfficiel}/></div>}<div className="space-y-2"><Label>Nom complet *</Label><Input required value={form.nomComplet} onChange={e=>setForm({...form,nomComplet:e.target.value})}/></div><div className="space-y-2"><Label>Sexe *</Label><Select required value={form.idSexe} onValueChange={v=>setForm({...form,idSexe:v})}><SelectTrigger><SelectValue placeholder="Sélectionner"/></SelectTrigger><SelectContent>{sexes.map(x=><SelectItem key={x.id} value={x.id}>{x.nom}</SelectItem>)}</SelectContent></Select></div>{date("dateNaissance","Date de naissance")}<div className="space-y-2"><Label>Lieu de naissance</Label><Input value={form.lieuNaissance} onChange={e=>setForm({...form,lieuNaissance:e.target.value})}/></div>{([['nationalite','Nationalité'],['idNational','ID national'],['idFivb','ID FIVB'],['telephone','Téléphone'],['email','Adresse e-mail'],['adresse','Adresse'],['numeroPasseport','Numéro de passeport'],['observations','Observations']] as const).map(([k,l])=><div key={k} className="space-y-2"><Label>{l}</Label><Input type={k==='email'?'email':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}{date("dateDelivrancePasseport","Date de délivrance")}{date("dateExpirationPasseport","Date d’expiration")}<AvatarFileField editing={editing} onFileChange={setAvatar}/><div className="space-y-2"><Label>Statut</Label><Select value={form.statut} onValueChange={v=>setForm({...form,statut:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ACTIF">Actif</SelectItem><SelectItem value="INACTIF">Inactif</SelectItem></SelectContent></Select></div></div>{error&&<p className="text-sm text-destructive">{error}</p>}<SheetFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Annuler</Button><Button disabled={pending} className="bg-brand-gold text-[#071827] hover:bg-brand-gold/90">{pending?"Enregistrement…":"Enregistrer"}</Button></SheetFooter></form></SheetContent></Sheet>}
