import "server-only"
import { env } from "@/lib/env"
import { appendSheetRecord, deleteSheetRecordById, getSheetsDataFrom, updateSheetRecordById, type SheetRow } from "@/lib/google-sheets"
import { formatDateForSheet } from "@/lib/compact-date"

export type ActivityOption = { id: string; label: string; secondary?: string }
export type ActivityView = { id:string;typeId:string;type:string;organizerId:string;organizer:string;name:string;publicTitle:string;summary:string;startDate:string;endDate:string;country:string;city:string;place:string;status:string;observations:string }
export type ActivityEntityView = { id:string;activityId:string;entityId:string;entity:string;roleId:string;role:string;participationStatus:string;observations:string }
export type ActivityParticipantView = { id:string;activityId:string;typeId:string;type:string;actorId:string;actor:string;participationRole:string;participationStatus:string;observations:string }
export type ActivityReferences = { types:ActivityOption[];entities:ActivityOption[];roles:ActivityOption[];actorTypes:ActivityOption[];actorsByType:Record<string,ActivityOption[]> }
const text=(row:SheetRow,key:string)=>String(row[key]??"").trim()
const labelFrom=(row:SheetRow,key:string)=>text(row,key)||Object.entries(row).find(([name,value])=>name.startsWith("nom_")&&String(value??"").trim())?.[1]?.toString().trim()||""
const options=(rows:SheetRow[],id:string,label:string)=>rows.map(row=>({id:text(row,id),label:labelFrom(row,label)})).filter(item=>item.id&&item.label)
const labels=(items:ActivityOption[])=>new Map(items.map(item=>[item.id,item.label]))

async function loadActivityReferences():Promise<ActivityReferences>{
  const[refs,territorial,actors]=await Promise.all([
    getSheetsDataFrom(env.googleSheets.referentielsSpreadsheetId,["TYPES_ACTIVITE!A:Z","ROLES_ENTITE_ACTIVITE!A:Z","TYPES_ACTEURS!A:Z"]),
    getSheetsDataFrom(env.googleSheets.territorialSpreadsheetId,["LIGUES!A:Z","ENTENTES!A:Z","CLUBS!A:Z"]),
    getSheetsDataFrom(env.googleSheets.acteursSpreadsheetId,["ATHLETES!A:Z","COACHS!A:Z","OFFICIELS!A:Z","ARBITRES!A:Z","MEDECINS!A:Z"]),
  ])
  const entities=[...options(territorial.LIGUES??[],"id_ligue","nom_ligue").map(x=>({...x,secondary:"Ligue"})),...options(territorial.ENTENTES??[],"id_entente","nom_entente").map(x=>({...x,secondary:"Entente"})),...options(territorial.CLUBS??[],"id_club","nom_club").map(x=>({...x,secondary:"Club"}))]
  const actorTypes=options(refs.TYPES_ACTEURS??[],"id_type_acteur","nom_type_acteur"),sources=new Map((refs.TYPES_ACTEURS??[]).map(row=>[text(row,"id_type_acteur"),text(row,"source_donnees")]))
  const idHeaders:Record<string,string>={ATHLETES:"id_athlete",COACHS:"id_coach",OFFICIELS:"id_officiel",ARBITRES:"id_arbitre",MEDECINS:"id_medecin"}
  const actorsByType=Object.fromEntries(actorTypes.map(type=>{const source=sources.get(type.id)??"",id=idHeaders[source];return[type.id,id?options(actors[source]??[],id,"nom_complet"):[]]}))
  return{types:options(refs.TYPES_ACTIVITE??[],"id_type_activite","nom_type_activite"),entities,roles:options(refs.ROLES_ENTITE_ACTIVITE??[],"id_role_entite_activite","nom_role_entite_activite"),actorTypes,actorsByType}
}

export async function loadActivities(){const[business,refs]=await Promise.all([getSheetsDataFrom(env.googleSheets.activitiesSpreadsheetId,["ACTIVITES!A:Z"]),getSheetsDataFrom(env.googleSheets.referentielsSpreadsheetId,["TYPES_ACTIVITE!A:Z"])]),typeOptions=options(refs.TYPES_ACTIVITE??[],"id_type_activite","nom_type_activite"),types=labels(typeOptions);const activities:ActivityView[]=(business.ACTIVITES??[]).map(row=>{const typeId=text(row,"id_type_activite"),organizerId=text(row,"id_entite_organisatrice");return{id:text(row,"id_activite"),typeId,type:types.get(typeId)??(typeId?"Type non reconnu":"—"),organizerId,organizer:organizerId,name:text(row,"nom_activite"),publicTitle:text(row,"titre_public"),summary:text(row,"resume"),startDate:text(row,"date_debut"),endDate:text(row,"date_fin"),country:text(row,"pays"),city:text(row,"ville"),place:text(row,"lieu"),status:text(row,"statut"),observations:text(row,"observations")}}).filter(item=>item.id);return{activities,typeOptions}}

export async function loadActivityDetail(id:string){const[bundle,relations,references]=await Promise.all([loadActivities(),getSheetsDataFrom(env.googleSheets.activitiesSpreadsheetId,["ACTIVITES_ENTITES!A:Z","ACTIVITES_PARTICIPANTS!A:Z"]),loadActivityReferences()]),activity=bundle.activities.find(item=>item.id===id);if(!activity)return undefined;const entityNames=labels(references.entities),roleNames=labels(references.roles),typeNames=labels(references.actorTypes),actorNames=new Map(Object.values(references.actorsByType).flat().map(item=>[item.id,item.label]));const entities:ActivityEntityView[]=(relations.ACTIVITES_ENTITES??[]).filter(row=>text(row,"id_activite")===id).map(row=>{const entityId=text(row,"id_entite"),roleId=text(row,"id_role_entite_activite");return{id:text(row,"id_activite_entite"),activityId:id,entityId,entity:entityNames.get(entityId)??entityId,roleId,role:roleNames.get(roleId)??roleId,participationStatus:text(row,"statut_participation"),observations:text(row,"observations")}});const participants:ActivityParticipantView[]=(relations.ACTIVITES_PARTICIPANTS??[]).filter(row=>text(row,"id_activite")===id).map(row=>{const typeId=text(row,"id_type_acteur"),actorId=text(row,"id_acteur");return{id:text(row,"id_participation"),activityId:id,typeId,type:typeNames.get(typeId)??typeId,actorId,actor:actorNames.get(actorId)??actorId,participationRole:text(row,"role_participation"),participationStatus:text(row,"statut_participation"),observations:text(row,"observations")}});return{activity,entities,participants,references}}

export function validateActivityInput(input:Record<string,unknown>){const value=(key:string)=>String(input[key]??"").trim(),errors:Record<string,string>={};const values={id_type_activite:value("id_type_activite"),id_entite_organisatrice:value("id_entite_organisatrice"),nom_activite:value("nom_activite"),titre_public:value("titre_public"),resume:value("resume"),date_debut:value("date_debut"),date_fin:value("date_fin"),pays:value("pays"),ville:value("ville"),lieu:value("lieu"),statut:value("statut")||"PLANIFIE",observations:value("observations")};if(!values.nom_activite)errors.nom_activite="Le nom est obligatoire.";if(!values.id_type_activite)errors.id_type_activite="Le type est obligatoire.";if(!values.date_debut)errors.date_debut="La date de début est obligatoire.";try{values.date_debut=formatDateForSheet(values.date_debut)}catch{errors.date_debut="Date invalide (JJMMAAAA)."}try{values.date_fin=values.date_fin?formatDateForSheet(values.date_fin):""}catch{errors.date_fin="Date invalide (JJMMAAAA)."}if(values.date_debut&&values.date_fin&&values.date_fin<values.date_debut)errors.date_fin="La fin doit être postérieure ou égale au début.";return{values,errors}}
const nextId=(existing:string[],prefix:string)=>`${prefix}${String(existing.reduce((max,id)=>Math.max(max,Number(id.replace(/^\D+/,""))||0),0)+1).padStart(4,"0")}`
export function nextActivityId(existing:string[],now=new Date()){const prefix=`VOL-ACT-${now.getFullYear()}-`,max=existing.filter(id=>id.startsWith(prefix)).reduce((n,id)=>Math.max(n,Number(id.slice(prefix.length))||0),0);return`${prefix}${String(max+1).padStart(6,"0")}`}
export async function createActivity(input:Record<string,unknown>){const{values,errors}=validateActivityInput(input);if(Object.keys(errors).length)return{errors};const bundle=await loadActivities();if(!bundle.typeOptions.some(item=>item.id===values.id_type_activite))return{errors:{id_type_activite:"Type inconnu."}};const id=nextActivityId(bundle.activities.map(item=>item.id));await appendSheetRecord(env.googleSheets.activitiesSpreadsheetId,"ACTIVITES",{id_activite:id,...values});return{id,errors:{}}}
export async function updateActivity(id:string,input:Record<string,unknown>){const{values,errors}=validateActivityInput(input);if(Object.keys(errors).length)return{errors};await updateSheetRecordById(env.googleSheets.activitiesSpreadsheetId,"ACTIVITES","id_activite",id,values);return{id,errors:{}}}
export async function saveActivityEntity(activityId:string,input:Record<string,unknown>,id?:string){const detail=await loadActivityDetail(activityId);if(!detail)throw new Error("Activité introuvable.");const entityId=String(input.id_entite??"").trim(),roleId=String(input.id_role_entite_activite??"").trim();if(!detail.references.entities.some(x=>x.id===entityId)||!detail.references.roles.some(x=>x.id===roleId))throw new Error("Entité ou rôle invalide.");if(detail.entities.some(x=>x.id!==id&&x.entityId===entityId&&x.roleId===roleId))throw new Error("Cette entité possède déjà ce rôle.");const record={id_activite:activityId,id_entite:entityId,id_role_entite_activite:roleId,statut_participation:String(input.statut_participation??"ACTIF"),observations:String(input.observations??"").trim()};if(id)await updateSheetRecordById(env.googleSheets.activitiesSpreadsheetId,"ACTIVITES_ENTITES","id_activite_entite",id,record);else{id=nextId(detail.entities.map(x=>x.id),"AEN");await appendSheetRecord(env.googleSheets.activitiesSpreadsheetId,"ACTIVITES_ENTITES",{id_activite_entite:id,...record})}return{id,...record}}
export async function removeActivityEntity(activityId:string,id:string){const detail=await loadActivityDetail(activityId);if(!detail?.entities.some(x=>x.id===id))throw new Error("Entité participante introuvable.");await deleteSheetRecordById(env.googleSheets.activitiesSpreadsheetId,"ACTIVITES_ENTITES","id_activite_entite",id)}
export async function saveActivityParticipant(activityId:string,input:Record<string,unknown>,id?:string){const detail=await loadActivityDetail(activityId);if(!detail)throw new Error("Activité introuvable.");const typeId=String(input.id_type_acteur??"").trim(),actorId=String(input.id_acteur??"").trim();if(!detail.references.actorsByType[typeId]?.some(x=>x.id===actorId))throw new Error("Participant ou type d’acteur invalide.");if(detail.participants.some(x=>x.id!==id&&x.actorId===actorId))throw new Error("Ce participant est déjà enregistré.");const record={id_activite:activityId,id_type_acteur:typeId,id_acteur:actorId,role_participation:String(input.role_participation??"").trim(),statut_participation:String(input.statut_participation??"ACTIF"),observations:String(input.observations??"").trim()};if(id)await updateSheetRecordById(env.googleSheets.activitiesSpreadsheetId,"ACTIVITES_PARTICIPANTS","id_participation",id,record);else{id=nextId(detail.participants.map(x=>x.id),"PAR");await appendSheetRecord(env.googleSheets.activitiesSpreadsheetId,"ACTIVITES_PARTICIPANTS",{id_participation:id,...record})}return{id,...record}}
