import "server-only"
import { getActorSexes } from "@/lib/actor-references"
import { nextActorId } from "@/lib/actor-id"
import { compareDateValues, formatDateForSheet, validateBirthDate } from "@/lib/compact-date"
import { getOfficiels } from "@/lib/data"
import { env } from "@/lib/env"
import { appendSheetRecord, formatSheetDateColumn, updateSheetRecordById } from "@/lib/google-sheets"

const text=(v:unknown)=>String(v??"").trim(), emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/
type Input={idNational:string;idFivb:string;nomComplet:string;idSexe:string;dateNaissance:string;lieuNaissance:string;nationalite:string;telephone:string;email:string;adresse:string;numeroPasseport:string;dateDelivrancePasseport:string;dateExpirationPasseport:string;statut:string;observations:string}
const normalizeInput=(p:Record<string,unknown>):Input=>({idNational:text(p.idNational),idFivb:text(p.idFivb),nomComplet:text(p.nomComplet),idSexe:text(p.idSexe),dateNaissance:text(p.dateNaissance??p.dateDeNaissance),lieuNaissance:text(p.lieuNaissance),nationalite:text(p.nationalite),telephone:text(p.telephone),email:text(p.email),adresse:text(p.adresse),numeroPasseport:text(p.numeroPasseport),dateDelivrancePasseport:text(p.dateDelivrancePasseport),dateExpirationPasseport:text(p.dateExpirationPasseport),statut:text(p.statut).toUpperCase()||"ACTIF",observations:text(p.observations)})
async function validate(x:Input){if(!x.nomComplet)throw new Error("Le nom complet est obligatoire.");if(!x.idSexe)throw new Error("Le sexe est obligatoire.");const e=validateBirthDate(x.dateNaissance);if(e)throw new Error(e);for(const [v,l] of [[x.dateDelivrancePasseport,"La date de délivrance"],[x.dateExpirationPasseport,"La date d’expiration"]] as const)if(v){try{formatDateForSheet(v)}catch{throw new Error(`${l} est invalide.`)}}if(x.dateDelivrancePasseport&&x.dateExpirationPasseport&&compareDateValues(x.dateDelivrancePasseport,x.dateExpirationPasseport)!>0)throw new Error("La date d’expiration ne peut pas précéder la délivrance.");if(x.email&&!emailPattern.test(x.email))throw new Error("L’adresse e-mail est invalide.");if(!new Set(["ACTIF","INACTIF"]).has(x.statut))throw new Error("Le statut est invalide.");const sexe=(await getActorSexes()).find(o=>o.id===x.idSexe);if(!sexe)throw new Error("Le sexe sélectionné est invalide.");return sexe}
const record=(x:Input)=>({id_national:x.idNational,id_fivb:x.idFivb,nom_complet:x.nomComplet,id_sexe:x.idSexe,date_naissance:x.dateNaissance?formatDateForSheet(x.dateNaissance):"",lieu_de_naissance:x.lieuNaissance,nationalite:x.nationalite,telephone:x.telephone,email:x.email,adresse:x.adresse,"numéro_passeport":x.numeroPasseport,date_de_delivrance_passeport:x.dateDelivrancePasseport?formatDateForSheet(x.dateDelivrancePasseport):"",date_expiration_passeport:x.dateExpirationPasseport?formatDateForSheet(x.dateExpirationPasseport):"",statut:x.statut,observations:x.observations})
async function formatDates(){await Promise.all([formatSheetDateColumn(env.googleSheets.acteursSpreadsheetId,"OFFICIELS","date_de_naissance","yyyy-mm-dd"),formatSheetDateColumn(env.googleSheets.acteursSpreadsheetId,"OFFICIELS","date_de_delivrance_passeport","yyyy-mm-dd"),formatSheetDateColumn(env.googleSheets.acteursSpreadsheetId,"OFFICIELS","date_expiration_passeport","yyyy-mm-dd")])}
export async function createOfficiel(p:Record<string,unknown>){const x=normalizeInput(p),sexe=await validate(x),all=await getOfficiels(),idOfficiel=nextActorId(all.map(o=>o.idOfficiel),"OFF");await formatDates();await appendSheetRecord(env.googleSheets.acteursSpreadsheetId,"OFFICIELS",{id_officiel:idOfficiel,...record(x)},"OVERWRITE");return (await getOfficiels()).find(o=>o.idOfficiel===idOfficiel)??{...x,idOfficiel,id:idOfficiel,idSexe:x.idSexe,sexe:sexe.nom,dateDeNaissance:x.dateNaissance?formatDateForSheet(x.dateNaissance):"",dateNaissance:x.dateNaissance?formatDateForSheet(x.dateNaissance):"",genre:sexe.nom,avatarDriveId:"",avatarDriveUrl:"",passeportDriveId:"",passeportDriveUrl:"",fonction:"",entite:"",rattachement:"",dateNomination:"",dateFinMandat:"",equipeFederal:""}}
export async function updateOfficiel(id:string,p:Record<string,unknown>){const current=(await getOfficiels()).find(o=>o.idOfficiel===id);if(!current)throw new Error("Officiel introuvable.");const x=normalizeInput({idNational:current.idNational,idFivb:current.idFivb,nomComplet:current.nomComplet,idSexe:current.idSexe,dateNaissance:current.dateDeNaissance,lieuNaissance:current.lieuNaissance,nationalite:current.nationalite,telephone:current.telephone,email:current.email,adresse:current.adresse,numeroPasseport:current.numeroPasseport,dateDelivrancePasseport:current.dateDelivrancePasseport,dateExpirationPasseport:current.dateExpirationPasseport,statut:current.statut,observations:current.observations,...p});await validate(x);await formatDates();await updateSheetRecordById(env.googleSheets.acteursSpreadsheetId,"OFFICIELS","id_officiel",id,record(x));return (await getOfficiels()).find(o=>o.idOfficiel===id)??{...current,...x,dateDeNaissance:x.dateNaissance?formatDateForSheet(x.dateNaissance):""}}
export async function updateOfficielAvatar(id:string,avatarDriveId:string,avatarDriveUrl:string){const current=(await getOfficiels()).find(o=>o.idOfficiel===id);if(!current)throw new Error("Officiel introuvable.");await updateSheetRecordById(env.googleSheets.acteursSpreadsheetId,"OFFICIELS","id_officiel",id,{avatar_drive_id:avatarDriveId,avatar_drive_url:avatarDriveUrl});return (await getOfficiels()).find(o=>o.idOfficiel===id)??{...current,avatarDriveId,avatarDriveUrl}}
