"use client"
import { useState } from "react"
import Link from "next/link"
import { CalendarRange, LockKeyhole, UserRound } from "lucide-react"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Separator } from "@/components/ui/separator"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog"
import { formatDateForDisplay } from "@/lib/compact-date"
import { canRequestSeasonChange, canSelectSeason, profileInitials, profileLabel, type SystemSettingsViewModel, type UserProfileViewModel } from "@/lib/settings-domain"

const readonlyHelp = <p className="text-xs text-muted-foreground">Cette information est gérée par l’administration.</p>
function ReadonlyField({ label, value, type = "text" }: { label: string; value?: string; type?: "text" | "email" | "tel" }) { return <div className="space-y-2"><Label>{label}</Label><Input type={type} value={value ?? ""} readOnly disabled aria-label={`${label}, lecture seule`} />{readonlyHelp}</div> }
function SummaryRow({ label, value }: { label: string; value: string }) { return <div className="grid gap-1 py-3 sm:grid-cols-[10rem_1fr] sm:items-center"><dt className="text-sm text-muted-foreground">{label}</dt><dd className="break-words text-sm font-medium">{value}</dd></div> }

export function SettingsClient({ profile, settings, error }: { profile: UserProfileViewModel; settings: SystemSettingsViewModel; error: string }) {
  const [selectedId, setSelectedId] = useState(settings.currentSeasonId ?? "")
  const selected = settings.availableSeasons.find((season) => season.id === selectedId)
  const changed = selectedId && selectedId !== settings.currentSeasonId && Boolean(selected && canSelectSeason(selected))
  const canSave = canRequestSeasonChange(settings, selectedId)
  const current = settings.currentSeason
  return <div className="mx-auto w-full max-w-6xl space-y-5">
    <nav aria-label="Fil d’Ariane" className="text-sm text-muted-foreground"><Link href="/" className="hover:text-foreground hover:underline">Accueil</Link><span aria-hidden="true" className="px-2">/</span><span aria-current="page" className="text-foreground">Paramètres</span></nav>
    {error ? <div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm"><p className="font-medium text-destructive">Impossible de charger les saisons disponibles.</p><p className="mt-1 text-muted-foreground">{error}</p></div> : null}
    <Card className="border-border/80 shadow-none"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><Avatar className="size-16 border border-primary/30"><AvatarImage src={profile.avatarUrl} alt="" /><AvatarFallback className="bg-primary/15 text-lg font-semibold text-primary">{profileInitials(profile)}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><h2 className="truncate text-xl font-semibold">{profileLabel(profile.fullName, "Utilisateur")}</h2><p className="text-sm text-muted-foreground">{profileLabel(profile.jobTitle, "Fonction non renseignée")}</p><div className="mt-2 flex flex-wrap gap-2"><Badge variant="secondary">{profileLabel(profile.roleLabel, "Rôle non renseigné")}</Badge><Badge variant="outline">{profileLabel(profile.entityLabel, "Structure non renseignée")}</Badge><Badge className="bg-success text-success-foreground">{profileLabel(profile.status, "Statut non renseigné")}</Badge></div></div></CardContent></Card>
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1.45fr)_minmax(19rem,.75fr)]">
      <div className="space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UserRound className="size-4 text-primary" aria-hidden="true" />Informations personnelles</CardTitle><CardDescription>Informations utilisées pour identifier votre compte dans le système.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><ReadonlyField label="Nom" value={profile.lastName} /><ReadonlyField label="Postnom" value={profile.middleName} /><ReadonlyField label="Prénom" value={profile.firstName} /><ReadonlyField label="Fonction" value={profile.jobTitle} /><ReadonlyField label="Adresse e-mail" value={profile.email} type="email" /><ReadonlyField label="Numéro de téléphone" value={profile.phone} type="tel" /></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><LockKeyhole className="size-4 text-primary" aria-hidden="true" />Accès et rattachement</CardTitle><CardDescription>Rôle, niveau d’accès et périmètre associés à votre compte.</CardDescription></CardHeader><CardContent><dl className="divide-y"><SummaryRow label="Rôle" value={profileLabel(profile.roleLabel, "Rôle non renseigné")} /><SummaryRow label="Niveau d’accès" value={profileLabel(profile.accessLevel, "Niveau non renseigné")} /><SummaryRow label="Type d’entité" value={profileLabel(profile.entityTypeLabel, "Type non renseigné")} /><SummaryRow label="Entité" value={profileLabel(profile.entityLabel, "Structure non renseignée")} /><SummaryRow label="Statut du compte" value={profileLabel(profile.status, "Statut non renseigné")} /></dl><p className="mt-4 text-xs text-muted-foreground">Contactez un administrateur pour modifier votre rôle ou votre périmètre d’accès.</p></CardContent></Card></div>
      <Card className="h-fit border-primary/30 bg-primary/[0.04]"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarRange className="size-5 text-primary" aria-hidden="true" />Saison courante</CardTitle><CardDescription>Détermine les données affichées par défaut dans les vues saisonnières.</CardDescription></CardHeader><CardContent className="space-y-5">{current ? <div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Saison utilisée actuellement</p><p className="mt-2 text-3xl font-semibold">{current.label}</p><p className="mt-1 text-sm text-muted-foreground">{current.startDate || current.endDate ? `Du ${formatDateForDisplay(current.startDate ?? "") || "—"} au ${formatDateForDisplay(current.endDate ?? "") || "—"}` : "Période non renseignée"}</p><Badge variant="secondary" className="mt-3">{current.statusLabel || "Statut non renseigné"}</Badge>{settings.lastUpdatedAt ? <p className="mt-3 text-xs text-muted-foreground">Dernière modification : {settings.lastUpdatedAt}{settings.lastUpdatedBy ? ` · ${settings.lastUpdatedBy}` : ""}</p> : null}</div> : <div role="status" className="rounded-md border border-warning/40 bg-warning/10 p-3 text-sm">Aucune saison courante n’est configurée.</div>}<Separator /><div className="space-y-2"><Label>Définir la saison courante</Label><Select value={selectedId} onValueChange={setSelectedId} disabled={!settings.seasonsAvailable || !settings.availableSeasons.length}><SelectTrigger className="w-full"><SelectValue placeholder="Sélectionner une saison" /></SelectTrigger><SelectContent>{settings.availableSeasons.map((season) => <SelectItem key={season.id} value={season.id} disabled={!canSelectSeason(season)}>{season.label}{season.statusLabel ? ` — ${season.statusLabel}` : ""}</SelectItem>)}</SelectContent></Select></div><AlertDialog><AlertDialogTrigger asChild><Button className="w-full bg-brand-gold text-slate-950 hover:bg-brand-gold/90" disabled={!changed || !settings.persistenceAvailable}>Définir comme saison courante</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Changer la saison courante ?</AlertDialogTitle><AlertDialogDescription>Vous êtes sur le point de définir la saison {selected?.label} comme saison courante. Cette modification changera les données affichées par défaut sans supprimer ni déplacer aucune donnée.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annuler</AlertDialogCancel><AlertDialogAction disabled={!canSave}>Confirmer le changement</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>{!settings.persistenceAvailable ? <div className="rounded-md border border-info/30 bg-info/10 p-3 text-xs text-muted-foreground"><p className="font-medium text-foreground">Interface prête — connexion aux données en attente.</p><p className="mt-1">La modification sera disponible après la connexion du service de paramètres.</p></div> : null}</CardContent></Card>
    </div>
  </div>
}
