"use client"
import { RefreshCw } from "lucide-react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { DataTable, type Column, type Filter } from "@/components/dashboard/data-table"
import { StatusBadge } from "@/components/dashboard/status-badge"
import type { ActorLicenceView } from "@/lib/licences-overview"
const columns: Column<ActorLicenceView>[] = [{ key: "acteur", header: "Acteur", className: "font-medium" }, { key: "type", header: "Type d’acteur" }, { key: "numero", header: "Numéro de licence" }, { key: "cycle", header: "Cycle" }, { key: "affiliation", header: "Affiliation" }, { key: "periode", header: "Période de validité" }, { key: "statut", header: "Statut enregistré", render: (row) => <StatusBadge status={row.statut} /> }, { key: "statutEffectif", header: "Statut effectif", render: (row) => <StatusBadge status={row.statutEffectif.replaceAll("_", " ")} /> }]
const options = (rows: ActorLicenceView[], key: keyof ActorLicenceView) => [...new Map(rows.filter((row) => row[key]).map((row) => [row[key], { value: String(row[key]), label: String(row[key]) }])).values()]
export function ActorLicencesClient({ rows, error }: { rows: ActorLicenceView[]; error: string }) { const router = useRouter(); if (error) return <Card className="border-destructive/40"><CardContent className="py-10 text-center"><p className="text-destructive">{error}</p><Button variant="outline" className="mt-4" onClick={() => router.refresh()}><RefreshCw />Réessayer</Button></CardContent></Card>; const filters: Filter[] = [{ key: "type", label: "Type", options: options(rows, "type") }, { key: "cycle", label: "Cycle", options: options(rows, "cycle") }, { key: "statutEffectif", label: "Statut", options: options(rows, "statutEffectif") }]; return <div className="space-y-6"><div className="flex justify-end"><Button variant="outline" onClick={() => router.refresh()}><RefreshCw />Actualiser</Button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total", rows.length], ["Valides", rows.filter((row) => row.statutEffectif === "VALIDE").length], ["À venir", rows.filter((row) => row.statutEffectif === "A_VENIR").length], ["Expirées", rows.filter((row) => row.statutEffectif === "EXPIREE").length]].map(([label, value]) => <Card key={label}><CardContent className="p-4"><p className="text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></CardContent></Card>)}</div><DataTable data={rows} columns={columns} filters={filters} idKey="id" searchPlaceholder="Nom, numéro ou identifiant…" /></div> }
