"use client"
import { RefreshCw } from "lucide-react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { DataTable, type Column, type Filter } from "@/components/dashboard/data-table"
import { StatusBadge } from "@/components/dashboard/status-badge"
import { formatDateForDisplay } from "@/lib/compact-date"
import type { AthleteLicenceView } from "@/lib/licences-overview"

const columns: Column<AthleteLicenceView>[] = [{ key: "athlete", header: "Athlète", className: "font-medium" }, { key: "numero", header: "Numéro de licence" }, { key: "saison", header: "Saison" }, { key: "club", header: "Club" }, { key: "entente", header: "Entente" }, { key: "ligue", header: "Ligue" }, { key: "sexe", header: "Sexe" }, { key: "dateDelivrance", header: "Délivrée le", render: (row) => formatDateForDisplay(row.dateDelivrance) || "—" }, { key: "statut", header: "Statut", render: (row) => <StatusBadge status={row.statut} /> }]
const options = (rows: AthleteLicenceView[], key: keyof AthleteLicenceView) => [...new Map(rows.filter((row) => row[key]).map((row) => [row[key], { value: String(row[key]), label: String(row[key]) }])).values()]
export function AthleteLicencesClient({ rows, error }: { rows: AthleteLicenceView[]; error: string }) { const router = useRouter(); if (error) return <Card className="border-destructive/40"><CardContent className="py-10 text-center"><p className="text-destructive">{error}</p><Button variant="outline" className="mt-4" onClick={() => router.refresh()}><RefreshCw />Réessayer</Button></CardContent></Card>; const filters: Filter[] = [{ key: "saison", label: "Saison", options: options(rows, "saison") }, { key: "statut", label: "Statut", options: options(rows, "statut") }, { key: "sexe", label: "Sexe", options: options(rows, "sexe") }, { key: "club", label: "Club", options: options(rows, "club") }, { key: "entente", label: "Entente", options: options(rows, "entente") }, { key: "ligue", label: "Ligue", options: options(rows, "ligue") }]; const unique = new Map(rows.map((row) => [`${row.athleteId}:${row.seasonId}`, row])); const values = [...unique.values()]; return <div className="space-y-6"><div className="flex justify-end"><Button variant="outline" onClick={() => router.refresh()}><RefreshCw />Actualiser</Button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total des licences", values.length], ["Athlètes masculins", values.filter((row) => /masculin|homme/i.test(row.sexe)).length], ["Athlètes féminins", values.filter((row) => /féminin|femme/i.test(row.sexe)).length], ["Licences actives", values.filter((row) => /active|actif|valide/i.test(row.statut)).length]].map(([label, value]) => <Card key={label}><CardContent className="p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>)}</div><DataTable data={rows} columns={columns} filters={filters} idKey="id" searchPlaceholder="Nom ou numéro de licence…" /></div> }
